#!/bin/bash -u
#
# Licensed GNU GPLv2; if you did not recieve a copy of the license, get one at http://www.gnu.org/licenses/gpl-2.0.html

hostname=$(hostname -s)
ip=$(getent hosts "$hostname" | awk '{print $1}')
cluster=ceph
fsid=$(awk '$1 == "fsid" {print $3}' /etc/ceph/ceph.conf)

if [ "${ip:0:4}" = "127." ]; then
    echo "ERROR: ip is local... deploy hosts file first"
    exit 1
fi
if [ -e "/var/lib/ceph/mon/${cluster}-${hostname}" ]; then
    echo "ERROR: a mon already exists here... aborting"
    exit 1
fi

tmp=/var/lib/ceph/tmp
# these paths are overwritten by puppet
monring2="/etc/ceph/${cluster}.mon.keyring"
adminring2="/etc/ceph/${cluster}.client.admin.keyring"
# these paths are not overwritten by puppet
adminring="${tmp}/${cluster}.client.admin.keyring"
monring="${tmp}/${cluster}.mon.keyring"

ceph-authtool --create-keyring "$monring" --gen-key -n mon. --cap mon 'allow *'
ceph-authtool --create-keyring "$adminring" --gen-key -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *'
ceph-authtool "$monring" --import-keyring "$adminring"
monmaptool --create --clobber --add "${hostname}" "$ip" --fsid "$fsid" "$tmp"/monmap
mkdir -p "/var/lib/ceph/mon/${cluster}-${hostname}"

ceph-mon --mkfs -i "${hostname}" --monmap "$tmp"/monmap --keyring "$monring"

touch "/var/lib/ceph/mon/${cluster}-${hostname}/done"
if which systemctl >/dev/null 2>&1; then
    touch "/var/lib/ceph/mon/${cluster}-${hostname}/systemd"
else
    touch "/var/lib/ceph/mon/${cluster}-${hostname}/sysvinit"
fi

chown -R ceph:ceph "/var/lib/ceph/mon/${cluster}-${hostname}"

cp "$monring" "$monring2"
cp "$adminring" "$adminring2"

if which systemctl >/dev/null 2>&1; then
    systemctl start "ceph-mon@${hostname}"
else
    service ceph start mon
fi

